const char *pgstrom_cuda_money_code =
  "/*\n"
  " * cuda_money.h\n"
  " *\n"
  " * Collection of currency functions for CUDA devices\n"
  " * --\n"
  " * Copyright 2011-2016 (C) KaiGai Kohei <kaigai@kaigai.gr.jp>\n"
  " * Copyright 2014-2016 (C) The PG-Strom Development Team\n"
  " *\n"
  " * This program is free software; you can redistribute it and/or modify\n"
  " * it under the terms of the GNU General Public License version 2 as\n"
  " * published by the Free Software Foundation.\n"
  " *\n"
  " * This program is distributed in the hope that it will be useful,\n"
  " * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
  " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
  " * GNU General Public License for more details.\n"
  " */\n"
  "#ifndef CUDA_MONEY_H\n"
  "#define CUDA_MONEY_H\n"
  "#ifdef __CUDACC__\n"
  "\n"
  "/* pg_money_t */\n"
  "#ifndef PG_MONEY_TYPE_DEFINED\n"
  "#define PG_MONEY_TYPE_DEFINED\n"
  "STROMCL_SIMPLE_TYPE_TEMPLATE(money, cl_long);\n"
  "STATIC_INLINE(Datum)\n"
  "pg_money_to_datum(cl_long value)\n"
  "{\n"
  "\treturn pg_int8_to_datum(value);\n"
  "}\n"
  "#endif\n"
  "\n"
  "/*\n"
  " * Cast function to currency data type\n"
  " */\n"
  "#ifdef PG_NUMERIC_TYPE_DEFINED\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_numeric_cash(kern_context *kcxt, pg_numeric_t arg1)\n"
  "{\n"
  "\n"
  "}\n"
  "#endif\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_int4_cash(kern_context *kcxt, pg_int4_t arg1)\n"
  "{\n"
  "\tpg_money_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (cl_long) arg1.value / (cl_long)PGLC_CURRENCY_SCALE;\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_int8_cash(kern_context *kcxt, pg_int8_t arg1)\n"
  "{\n"
  "\tpg_money_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (cl_long) arg1.value / (cl_long)PGLC_CURRENCY_SCALE;\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "/*\n"
  " * Currency operator functions\n"
  " */\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_cash_pl(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_money_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = arg1.value + arg2.value;\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_cash_mi(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_money_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = arg1.value + arg2.value;\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_float8_t)\n"
  "pgfn_cash_div_cash(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_float8_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tif (arg2.value == 0)\n"
  "\t\t{\n"
  "\t\t\tresult.isnull = true;\n"
  "\t\t\tSTROM_SET_ERROR(&kcxt->e, StromError_CpuReCheck);\n"
  "\t\t}\n"
  "\t\telse\n"
  "\t\t{\n"
  "\t\t\tresult.isnull = false;\n"
  "\t\t\tresult.value = (cl_double)arg1.value / (cl_double)arg2.value;\n"
  "\t\t}\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "#define PGFN_MONEY_MULFUNC_TEMPLATE(name,d_type)\t\t\t\t\t\\\n"
  "\tSTATIC_FUNCTION(pg_money_t)\t\t\t\t\t\t\t\t\t\t\\\n"
  "\tpgfn_cash_mul_##name(kern_context *kcxt,\t\t\t\t\t\t\\\n"
  "\t\t\t\t\t\t pg_money_t arg1, pg_##d_type##_t arg2)\t\t\\\n"
  "\t{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\tpg_money_t\tresult;\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\tif (arg1.isnull || arg2.isnull)\t\t\t\t\t\t\t\t\\\n"
  "\t\t\tresult.isnull = true;\t\t\t\t\t\t\t\t\t\\\n"
  "\t\telse\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\tresult.isnull = false;\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\tresult.value =  arg1.value * arg2.value;\t\t\t\t\\\n"
  "\t\t}\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\treturn result;\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t}\n"
  "\n"
  "PGFN_MONEY_MULFUNC_TEMPLATE(int2, int2)\n"
  "PGFN_MONEY_MULFUNC_TEMPLATE(int4, int4)\n"
  "//PGFN_MONEY_MULFUNC_TEMPLATE(int8, int8)\n"
  "PGFN_MONEY_MULFUNC_TEMPLATE(flt4, float4)\n"
  "PGFN_MONEY_MULFUNC_TEMPLATE(flt8, float8)\n"
  "#undef PGFN_MONEY_MULFUNC_TEMPLATE\n"
  "\n"
  "#define PGFN_MONEY_DIVFUNC_TEMPLATE(name,d_type,zero)\t\t\t\t\\\n"
  "\tSTATIC_FUNCTION(pg_money_t)\t\t\t\t\t\t\t\t\t\t\\\n"
  "\tpgfn_cash_div_##name(kern_context *kcxt,\t\t\t\t\t\t\\\n"
  "\t\t\t\t\t\t pg_money_t arg1, pg_##d_type##_t arg2)\t\t\\\n"
  "\t{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\tpg_money_t\tresult;\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\tif (arg1.isnull || arg2.isnull)\t\t\t\t\t\t\t\t\\\n"
  "\t\t\tresult.isnull = true;\t\t\t\t\t\t\t\t\t\\\n"
  "\t\telse\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\tif (arg2.value == (zero))\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t\tresult.isnull = true;\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t\tSTROM_SET_ERROR(&kcxt->e, StromError_CpuReCheck);\t\\\n"
  "\t\t\t}\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\telse\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t\tresult.isnull = false;\t\t\t\t\t\t\t\t\\\n"
  "\t\t\t\tresult.value =  arg1.value / arg2.value;\t\t\t\\\n"
  "\t\t\t}\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\t}\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t\treturn result;\t\t\t\t\t\t\t\t\t\t\t\t\\\n"
  "\t}\n"
  "\n"
  "PGFN_MONEY_DIVFUNC_TEMPLATE(int2, int2, 0)\n"
  "PGFN_MONEY_DIVFUNC_TEMPLATE(int4, int4, 0)\n"
  "//PGFN_MONEY_DIVFUNC_TEMPLATE(int8, int8, 0)\n"
  "PGFN_MONEY_DIVFUNC_TEMPLATE(flt4, float4, 0.0)\n"
  "PGFN_MONEY_DIVFUNC_TEMPLATE(flt8, float8, 0.0)\n"
  "#undef PGFN_MONEY_DIVFUNC_TEMPLATE\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_int2_mul_cash(kern_context *kcxt, pg_int2_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\treturn pgfn_cash_mul_int2(kcxt, arg2, arg1);\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_int4_mul_cash(kern_context *kcxt, pg_int4_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\treturn pgfn_cash_mul_int4(kcxt, arg2, arg1);\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_flt4_mul_cash(kern_context *kcxt, pg_float4_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\treturn pgfn_cash_mul_flt4(kcxt, arg2, arg1);\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_money_t)\n"
  "pgfn_flt8_mul_cash(kern_context *kcxt, pg_float8_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\treturn pgfn_cash_mul_flt8(kcxt, arg2, arg1);\n"
  "}\n"
  "\n"
  "/*\n"
  " * Currency comparison functions\n"
  " */\n"
  "STATIC_FUNCTION(pg_int4_t)\n"
  "pgfn_cash_cmp(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_int4_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value > arg2.value ? 1 :\n"
  "\t\t\t\t\t\targ1.value < arg2.value ? -1 : 0);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_bool_t)\n"
  "pgfn_cash_eq(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_bool_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value == arg2.value);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_bool_t)\n"
  "pgfn_cash_ne(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_bool_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value != arg2.value);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_bool_t)\n"
  "pgfn_cash_lt(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_bool_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value < arg2.value);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_bool_t)\n"
  "pgfn_cash_le(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_bool_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value <= arg2.value);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_bool_t)\n"
  "pgfn_cash_gt(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_bool_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value > arg2.value);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "STATIC_FUNCTION(pg_bool_t)\n"
  "pgfn_cash_ge(kern_context *kcxt, pg_money_t arg1, pg_money_t arg2)\n"
  "{\n"
  "\tpg_bool_t\tresult;\n"
  "\n"
  "\tif (arg1.isnull || arg2.isnull)\n"
  "\t\tresult.isnull = true;\n"
  "\telse\n"
  "\t{\n"
  "\t\tresult.isnull = false;\n"
  "\t\tresult.value = (arg1.value >= arg2.value);\n"
  "\t}\n"
  "\treturn result;\n"
  "}\n"
  "\n"
  "#else\t/* __CUDACC__ */\n"
  "#include \"utils/pg_locale.h\"\n"
  "\n"
  "STATIC_INLINE(void)\n"
  "assign_moneylib_session_info(StringInfo buf)\n"
  "{\n"
  "\tstruct lconv *lconvert = PGLC_localeconv();\n"
  "\tcl_int\t\tfpoint;\n"
  "\tcl_long\t\tscale;\n"
  "\tcl_int\t\ti;\n"
  "\n"
  "\t/* see comments about frac_digits in cash_in() */\n"
  "\tfpoint = lconvert->frac_digits;\n"
  "\tif (fpoint < 0 || fpoint > 10)\n"
  "\t\tfpoint = 2;\n"
  "\n"
  "\t/* compute required scale factor */\n"
  "\tscale = 1;\n"
  "\tfor (i=0; i < fpoint; i++)\n"
  "\t\tscale *= 10;\n"
  "\n"
  "\tappendStringInfo(\n"
  "\t\tbuf,\n"
  "\t\t\"#ifdef __CUDACC__\\n\"\n"
  "\t\t\"/* ================================================\\n\"\n"
  "\t\t\" * session information for cuda_money.h\\n\"\n"
  "\t\t\" * ================================================ */\\n\"\n"
  "\t\t\"\\n\"\n"
  "\t\t\"#define PGLC_CURRENCY_SCALE_LOG10  %d\\n\"\n"
  "\t\t\"#define PGLC_CURRENCY_SCALE        %ld\\n\"\n"
  "\t\t\"\\n\"\n"
  "\t\t\"#endif /* __CUDACC__ */\\n\",\n"
  "\t\tfpoint,\n"
  "\t\tscale);\n"
  "}\n"
  "#endif\t/* __CUDACC__ */\n"
  "#endif\t/* CUDA_MONEY_H */\n"
;
