const char *pgstrom_cuda_terminal_code =
  "/*\n"
  " * cuda_terminal.h\n"
  " *\n"
  " * CUDA device code to be located on end of the code block\n"
  " * --\n"
  " * Copyright 2011-2016 (C) KaiGai Kohei <kaigai@kaigai.gr.jp>\n"
  " * Copyright 2014-2016 (C) The PG-Strom Development Team\n"
  " *\n"
  " * This program is free software; you can redistribute it and/or modify\n"
  " * it under the terms of the GNU General Public License version 2 as\n"
  " * published by the Free Software Foundation.\n"
  " *\n"
  " * This program is distributed in the hope that it will be useful,\n"
  " * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
  " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
  " * GNU General Public License for more details.\n"
  " */\n"
  "#ifndef CUDA_TERMINAL_H\n"
  "#define CUDA_TERMINAL_H\n"
  "\n"
  "#ifndef CUDA_NUMERIC_H\n"
  "/*\n"
  " * pg_numeric_to_varlena - has to be defined in cuda_numeric.h if NUMERIC\n"
  " * data type is required, however, kern_form_heaptuple need to call this\n"
  " * function to treat internal representation of NUMERIC type.\n"
  " * The function below is a dummy alternative not to be called.\n"
  " */\n"
  "STATIC_FUNCTION(cl_uint)\n"
  "pg_numeric_to_varlena(kern_context *kcxt, char *vl_buffer,\n"
  "                      Datum value, cl_bool isnull)\n"
  "{\n"
  "\tSTROM_SET_ERROR(&kcxt->e, StromError_WrongCodeGeneration);\n"
  "\treturn 0;\n"
  "}\n"
  "#endif\n"
  "\n"
  "#endif\t/* CUDA_TERMINAL_H */\n"
;
